### ISSUE TITLE
【UI优化建议】：减小标题大小、隐藏面包屑同级内容、支持隐藏标题前图标

### ISSUE THREAD

**Issue by mozhux** [Misuzu2027/syplugin-backlink-panel#1]
如题
1. 标题字体目前过大：建议与当前默认保持一致。同时标题左边的图标建议能设置隐藏，不然和侧栏面板重复有点多余，现在主题很多隐藏了
![image](https://github.com/user-attachments/assets/cc6e1d9c-d011-495a-82a7-6efb9b6b82a2)
![image](https://github.com/user-attachments/assets/8d27cd06-229c-4709-97ec-cf0dcbea8978)

2.建议隐藏面包屑的同级内容，不然和下面的正文重复了。可参考savor主题。
![image](https://github.com/user-attachments/assets/cfd5cefb-3382-4e51-94f8-763b1cc9d8d9)
![image](https://github.com/user-attachments/assets/694909c5-ea75-4167-8258-511c0fa015d5)

**Comment by Misuzu2027** [comment]
1. 字体大小已调整。  调整页面结构与官方类似，使主题隐藏图标的css 可以生效（使用官方主题还是会显示）。
2. 调整页面结构与官方类似，使主题隐藏面包屑css 生效。

v0.0.2 已更新上线，麻烦看看还有没有问题。

**Comment by mozhux** [comment]
> 1. 字体大小已调整。  调整页面结构与官方类似，使主题隐藏图标的css 可以生效（使用官方主题还是会显示）。
> 2. 调整页面结构与官方类似，使主题隐藏面包屑css 生效。
> 
> v0.0.2 已更新上线，麻烦看看还有没有问题。

整体感觉很好。自然很多
