### ISSUE TITLE
筛选“动态锚文本”、“静态锚文本”失效

### ISSUE THREAD

**Issue by Nyeilim** [Misuzu2027/syplugin-backlink-panel#10]
思源：v3.1.9
如图，该页面选择“所有”，有 4 个反链，但是无论选择 “动态锚文本” 还是 “静态锚文本” 都是 0 个反链，尝试重启无效。
![image](https://github.com/user-attachments/assets/78fa1ddf-2d81-4ab4-a10e-fc344da92e9d)
![image](https://github.com/user-attachments/assets/eadf02a1-7c21-4cd3-b023-beb8d8e82baf)
![image](https://github.com/user-attachments/assets/77fade0f-63a8-455d-bd9a-5c5d7373c284)

**Comment by Misuzu2027** [comment]
v0.0.9 已修复
