### ISSUE TITLE
筛选面板 UI 图标无显示、提示文本被遮蔽

### ISSUE THREAD

**Issue by Nyeilim** [Misuzu2027/syplugin-backlink-panel#11]
思源版本：v3.1.9，采用默认主题
![image](https://github.com/user-attachments/assets/448e1474-9ae4-4c4e-9ab5-2851fa36b773)
![image](https://github.com/user-attachments/assets/c3d05c61-6aed-450f-b0e9-e2a2f650dab7)
![image](https://github.com/user-attachments/assets/6bb76c72-0ee4-4679-b147-e84fb5399193)

**Comment by Misuzu2027** [comment]
v0.0.9 已优化
