### ISSUE TITLE
在搜索界面底部反链面板显示的是错误的信息

### ISSUE THREAD

**Issue by SaXz2** [Misuzu2027/syplugin-backlink-panel#16]
![image](https://github.com/user-attachments/assets/05b3897a-da01-4e43-954e-ed292bab8aa5)

**Comment by SaXz2** [comment]
已手动更新至0.10最新版

**Comment by Misuzu2027** [comment]
v0.0.11 已修复

**Comment by Misuzu2027** [comment]
😇 刚发布了。
