### ISSUE TITLE
底部反链面板无法设置“始终显示”

### ISSUE THREAD

**Issue by QMike0** [Misuzu2027/syplugin-backlink-panel#18]
当关闭`插件设置`中的`文档底部显示反链面板`，但打开特定文档的`始终显示该文档底部反链`时，不能像之前那样显示底部反链面板。
即，设置如下：
![image](https://github.com/user-attachments/assets/9b625664-4dae-4bd1-8dc3-b05c27c2fa0a)
![image](https://github.com/user-attachments/assets/ad50faf9-8bd3-4e29-b60a-b9e43ceacca8)
现在必须在`插件设置`中打开`文档底部显示反链面板`才能正常显示底部反链

思源：v 3.1.10
本插件：v 0.0.11

**Comment by Misuzu2027** [comment]
v0.0.12 修复了
