### ISSUE TITLE
【UI优化建议】同文档的一个页面展示

### ISSUE THREAD

**Issue by mozhux** [Misuzu2027/syplugin-backlink-panel#2]
如题，目前同文档的反链被分开展示了，建议和默认的保持一致，并在文档右侧增加计数，提高空间利用率。
![image](https://github.com/user-attachments/assets/9f849edd-deb2-459c-bc56-2cf9e43dd5a8)
![image](https://github.com/user-attachments/assets/022892ba-c36b-4012-a533-308006dc1807)

**Comment by Misuzu2027** [comment]
这个是刻意如此的，劲量弱化了文档的概念，因为同一个文档的多个反链，更新时间、创建时间可能相差较大，使用修改（创建）时间排序，是根据反链块的修改和创建时间来排序的；如果以文档分组，可能会出现许多不想干的干扰项。

如果想要精确到某个文档，可以在筛选面板指定文档，同时筛选面板的文档块显示了反链块的数量。

**Comment by mozhux** [comment]
> 这个是刻意如此的，劲量弱化了文档的概念，因为同一个文档的多个反链，更新时间、创建时间可能相差较大，使用修改（创建）时间排序，是根据反链块的修改和创建时间来排序的；如果以文档分组，可能会出现许多不想干的干扰项。
> 
> 如果想要精确到某个文档，可以在筛选面板指定文档，同时筛选面板的文档块显示了反链块的数量。

好的，那就按原意思就行。
