### ISSUE TITLE
界面改进反馈

### ISSUE THREAD

**Issue by SaXz2** [Misuzu2027/syplugin-backlink-panel#21]
![Clip_2024-11-10_00-04-29](https://github.com/user-attachments/assets/6d72c9df-54a7-4bb9-b6a0-edc9770acf04)

有人觉得UI有些臃肿，我个人也有点感觉不够简洁，所以自己捣鼓了一下样式，希望大佬可以参考稍微优化一些

1.去除筛选界面的悬浮阴影
![Clip_2024-11-10_00-27-41](https://github.com/user-attachments/assets/7464ff49-8d95-4051-9675-18cd361a49df)

2.去掉不必掉的横线（顶部和截图中）
![Clip_2024-11-10_01-14-10](https://github.com/user-attachments/assets/06b0da07-9f8b-4682-90fa-9390310dcc13)

3.保持统一使用圆角

4.缩窄边框

5.降低筛选列表的透明度，直接修改会导致不同主题出现bug

6. 保存样式按钮单独占一行过于浪费，修改为按钮。

以下是稍微调整过的样式参考

![Clip_2024-11-10_01-08-42](https://github.com/user-attachments/assets/4c8f31c5-3436-4e07-a9f7-ab879fb42ae2)
![Clip_2024-11-10_01-20-36](https://github.com/user-attachments/assets/0649eff1-19ad-4d13-99b9-01862c7c6312)
![Clip_2024-11-10_01-29-27](https://github.com/user-attachments/assets/b81600a8-4b21-482c-901d-45fb3fea4fdc)
![Clip_2024-11-10_01-37-41](https://github.com/user-attachments/assets/40ba9633-5cec-47aa-8c33-30729c91253f)

原版对比
![Clip_2024-11-10_01-39-30](https://github.com/user-attachments/assets/46e5b072-2e70-47d2-b4fe-6afd7378b904)

**Comment by SaXz2** [comment]
@QMike0  我实测了几天你的想法，可以说很棒
![Clip_2024-11-14_00-00-00](https://github.com/user-attachments/assets/05ff3362-45f5-41d1-939a-d0243e7ac31f)

**Comment by Misuzu2027** [comment]
5. 降低筛选列表的透明度，直接修改会导致不同主题出现bug
  * 这个好像没有设置透明度，不太清楚啥原因。

6. 保存样式按钮单独占一行过于浪费，修改为按钮。
  * 这个现在就是按钮吧，调整为了保存的条件跟按钮在一行，可以多利用一些空间。


v0.0.19 版本优化了一下，主要是优化下面界面：

> 1.去除筛选界面的悬浮阴影
> 2.去掉不必掉的横线（顶部和截图中）
> 3.保持统一使用圆角
> 4.缩窄边框

**Comment by SaXz2** [comment]
5. 降低筛选列表的透明度，直接修改会导致不同主题出现bug
![Clip_2024-11-19_17-20-54](https://github.com/user-attachments/assets/03f1dde8-8101-455d-a2ff-2885826d2516)
这里我指的是图上红色部分的透明度，我没说明白，用opacity就行了，直接改颜色的话会导致没有颜色继承，改这里的原因是跟菜单进行区分，看着直观一些不然亮度统一，文档名称都是一样的亮度就会显得很平很乱
![Clip_2024-11-19_17-28-53](https://github.com/user-attachments/assets/371a124f-aa79-421e-94fc-ae19ccab0e6b)

**Comment by Misuzu2027** [comment]
明白了，是指字体的颜色完全一样，导致看起来没有层次，所以用透明度来调整黑度或白字时的亮度。我先改成默认 opacity: 0.9; 。如果觉得不够也是可以自定义 css 调整的，不会干扰其他主题样式：
```css
.backlink-panel__area .defblock-list .tag{
  opacity: 0.9;
}
```
