### ISSUE TITLE
请求添加 默认折叠反链面板的功能

### ISSUE THREAD

**Issue by SaXz2** [Misuzu2027/syplugin-backlink-panel#22]
有时候在浮窗中查看不太需要看到反链面板，但是反链面板又会变得很长，默认折叠也会减少一些卡顿的情况，希望添加

**Comment by SaXz2** [comment]
我觉得方案三就足够了改一改筛选面板默认展开的逻辑就成型了，前两个的话有点费力不讨好，在群里问了一下基本都是以3为主

**Comment by Misuzu2027** [comment]
试了一下，感觉还是需要区分一下面板是在哪里展示的，比如 侧边栏Dock 或 页签Tab 中展示面板，反链区域就没必要默认折叠了吧。

在浮窗、文档底部等，默认折叠就没啥问题。

**Comment by Misuzu2027** [comment]
打算使用这种方案，

4. 提供设置项开关∶ “文档底部默认展开反链面板 ”。保持 “默认展开筛选面板” 命名风格一致。

**Comment by Misuzu2027** [comment]
v0.0.16 已更新

**Comment by SaXz2** [comment]
> 试了一下，感觉还是需要区分一下面板是在哪里展示的，比如 侧边栏Dock 或 页签Tab 中展示面板，反链区域就没必要默认折叠了吧。
> 
> 在浮窗、文档底部等，默认折叠就没啥问题。

主要是这样写的话会非常麻烦，考虑到一些别的情况，有些人需要再浮窗中展开有些不需要，到时候再反复改太遭罪了，加一个按钮先看看后续有没有必要就行，0.0.16的修改方式就足够了

**Comment by SaXz2** [comment]
今天用下来还是感觉需要对浮窗进行处理的，因为会产生大量的滚动条

**Comment by Misuzu2027** [comment]
超过几条内容不好判断，把 “文档底部默认展开反链面板 ” 改成 “浮窗底部默认展开反链面板” 吧，精确到浮窗。

**Comment by SaXz2** [comment]
别改！！！ ，我很需要默认折叠，CSS也已经解决这个问题了

**Comment by Misuzu2027** [comment]
😂 ok

**Comment by SaXz2** [comment]
> 😂 ok

https://github.com/Misuzu2027/syplugin-backlink-panel/issues/13 这个实现以后咱们再考虑考虑这个，目前我觉得已经是最强的反链面板了
