### ISSUE TITLE
BUG: 创建页签后右键移动到新窗口后内容会变空

### ISSUE THREAD

**Issue by SaXz2** [Misuzu2027/syplugin-backlink-panel#23]
![Clip_2024-11-10_20-56-33](https://github.com/user-attachments/assets/32d7a274-e1bd-4c9c-a449-bc01a3d415af)

**Comment by Misuzu2027** [comment]
深入研究了一下，这应该是官方插件系统的机制问题，目前无法做到动态页签可以在新窗口中打开。

动态页签解释：根据不同条件生成模板相同，但是内容不同的页签。

原因：动态页签是在需要的时候才会进行初始化，比如选中某一篇文档，知道了文档的ID，不同文档生成不同的插件页签（id不同），就可以做到一个窗口同时存在多个插件页签。但是创建新窗口时，插件初始化的时候无法获取到之前初始化页签的条件进行添加插件页签，所以就会导致思源找不到该页签，页面一片空白。我试了下集市其他动态页签的插件也是如此。

如果想要做到插件页签能够在新窗口中打开，代价就是一个窗口同时只能显示一个反链页签。我感觉这样更不方便，**建议先把文档在新窗口打开，然后在新窗口使用快捷键（默认 ALT + SHIFT + T）来给这篇文档打开反链面板页签。**
