### ISSUE TITLE
添加选项或保持跟设置中一样 "反向链接包含子块"

### ISSUE THREAD

**Issue by SaXz2** [Misuzu2027/syplugin-backlink-panel#24]
现在的逻辑是默认关闭的状态没有其他设置方法

应该跟思源新版中的设置保持一致，设置中关闭就是关闭，开启则保持开启，或者添加按钮但好像没啥必要

![Clip_2024-11-11_16-51-54](https://github.com/user-attachments/assets/19430663-d6c9-4e94-add0-966a36a869b4)

**Comment by cordinGH** [comment]
想到一个可能有效的改进方案：当关闭包含子块后，筛选面板默认选中“包含文档块”（左图）。
![image](https://github.com/user-attachments/assets/e7a45eb7-9a18-491a-bbe0-ee8cfb3c16e3)
不知道有没有更合适的方案。

**Comment by cordinGH** [comment]
好处是如果想查看子块反链了，单击一下取消包含即可，不用去思源设置里面调了。

**Comment by Misuzu2027** [comment]
> 想到一个可能有效的改进方案：当关闭包含子块后，筛选面板默认选中 "文档块"（左图）

我觉得这个方案非常不错，就新增一个设置项：默认选中查看块

开启后就是图中的效果。
