### ISSUE TITLE
希望反链面板支持按锚文本内容过滤

### ISSUE THREAD

**Issue by Imuvux** [Misuzu2027/syplugin-backlink-panel#25]
**需求**：目前基于定义块也就是被引块的包含排除都很好用了，不过在锚文本过滤这方面只能筛选动态锚文本、静态锚文本，而内容过滤与锚文本过滤有一些差异，且目前也只能以包含为条件不能以排除为条件，因此希望能补上对包含、排除有指定内容的锚文本的筛选。当然也可以在块筛选面板和反链面板中间单开一个锚文本筛选面板，这样既能按相同逻辑设置包含排除，也能默认折叠防止文本过多太占空间。

**分析**：反链作为一个起汇总作用的功能，其实用性不仅取决于汇总能力更取决于过滤能力，因而反链的筛选是重中之重。Conor工作流会用`*`锚文本表示引用重述，[这个Issue](https://github.com/siyuan-note/siyuan/issues/10708)也隐含着想把不同显示效果的双链用作不同类型双链的需求。双链作为一个底层性语法而非业务性功能，其用途并非不言自明的，只能人为定义具体用法，因而才会用不同锚文本符号用作区分。除了`*`锚文本，还可能有`#`开头的锚文本像标签一样用，有`@`开头的锚文本用作其他一些功能，最好能对锚文本进行筛选比如过滤或排除包含`*`的锚文本。

目前插件只能筛选包含不能排除过滤，而且正文里的符号和锚文本的符号也不是一回事，最好还是能实现锚文本过滤。

**Comment by Misuzu2027** [comment]
我觉得针对 反向链接面板 下的输入框，新增一些搜索语法可以满足这个需求。

普通输入就是反链块中匹配；感叹号(中英文都算)加关键字就是排除这个关键字；小括号(中英文都算)包裹的关键字就只匹配反链块中定义块的锚文本。

例子：
* 芒果 白菜
  * 反链块中同时包含 芒果 白菜 
* !芒果  白菜
  * 反链块中不包含 芒果，包含 白菜。
* (*) 白菜
  * 反链块中包含 白菜，同时反链块中有定义块的锚文本包含 *


麻烦看下觉得如何，能否满足需求。

**Comment by Imuvux** [comment]
如果锚文本匹配也能排除就非常好，比如`(!*)`能排除存在“锚文本里有`*`的定义块”的反链，这就和思源原生的块引用转换为`*`完美联动起来了。也就是小括号用来在锚文本里执行与反链同样逻辑的匹配。

然后这样的话可能需要加一个语法说明，类似番茄工具箱的底部反链的搜索语法提示。

其实我感觉目前各种插件里底部反链的功能说明都还是不够清楚，比如：

* 『定义块』的概念

定义块是指被引用块，即正链指向的块本体。如果反链中有查询到对本文档内容的块引用，那么其定义块会出现在筛选面板。

* 『定义块』的筛选与操作

有“包含、排除、待选中”三种状态，可以同时对多个定义块使用。

* 『关联的定义块』

如果本文档的反链中有查询到对其他文档内容的块引用，那么其定义块会出现在筛选面板-关联的定义块。

如果在插件设置中启用查询父级关联定义块，那么反链面板中一个反链的上级路径中的所有引用的定义块也会出现在筛选面板。

* 反链内容和锚文本的筛选语法

**Comment by Misuzu2027** [comment]
好的，会增加针对锚文本的排除， 思考了一下，匹配锚文本用 ( )  解析起来麻烦，输入起来也不方便，打算换个符号当前缀，

* `-` ：排除
* `!` ：匹配锚文本
* `!-` 或 `-!` ：排除锚文本

如果有其他符号建议可以回复。

感谢提供说明，后续会更新到 说明文档 中。

**Comment by Imuvux** [comment]
符号的话一方面和其他插件一致比较好不用重学，另一方面短横线挺常用的不一定适合赋予语义。所以我建议叹号`!`就表示排除，锚文本可以用`%`标识。效果：

| 筛选语法前缀 | 反链内容 | 锚文本内容 |
| ---------- | ---------- | ------------ |
| 包含     | 无前缀   | `%`           |
| 排除     | `!`或`！`       | `%!`或`!%`或`%！`或`！%`     |

**Comment by Misuzu2027** [comment]
这个确实不太好权衡，我看简易搜索是 `-` 排除， 番茄工具箱的底部反链是 `!`  排除。

**Comment by Misuzu2027** [comment]
排除语法还是打算用 `-` ，我看了下 Obsidian、谷歌 的搜索语法都是用 `-` 来排除。 匹配锚文本符号用 ！ 还是  % 犹豫一下。

**Comment by Imuvux** [comment]
> 匹配锚文本符号用 ！ 还是 % 犹豫一下。

个人感觉用`%`的话不用考虑中英文问题，可能方便一点

**Comment by cordinGH** [comment]
@Imuvux 不知道您有没有使用过插件里 “关联的定义块” 这个功能？我觉得这个功能是能够满足你的需求。

**Comment by Imuvux** [comment]
> 不知道您有没有使用过插件里 “关联的定义块” 这个功能？我觉得这个功能是能够满足锚文本过滤的需求的。

关联的定义块指的是本反链上下文中的其他引用定义块，和本反链的块引用无关，也和本反链的锚文本无关，可能你没有理解我的需求用法。假设我在文档A里引用文档B，后来将引用右键转成`*`锚文本，那么文档B的反链面板里会出现A的以`*`为锚文本的反链；而你说的关联的定义块里完全不会出现东西，导致我不能排除这类反链，所以提出了这个Issue。现在的版本已经能对锚文本进行筛选过滤了，潜在问题是其筛选范围为所有锚文本而非当前反链的锚文本，这才是关联的定义块有用的点。

**Comment by cordinGH** [comment]
> > 不知道您有没有使用过插件里 “关联的定义块” 这个功能？我觉得这个功能是能够满足锚文本过滤的需求的。
> 
> 关联的定义块指的是本反链上下文中的其他引用定义块，和本反链的块引用无关，也和本反链的锚文本无关，可能你没有理解我的需求用法。假设我在文档A里引用文档B，后来将引用右键转成`*`锚文本，那么文档B的反链面板里会出现A的以`*`为锚文本的反链；而你说的关联的定义块里完全不会出现东西，导致我不能排除这类反链，所以提出了这个Issue。现在的版本已经能对锚文本进行筛选过滤了，潜在问题是其筛选范围为所有锚文本而非当前反链的锚文本，这才是关联的定义块有用的点。

有道理，这确实是个不错的使用场景👍
