### ISSUE TITLE
对功能布局的优化建议

### ISSUE THREAD

**Issue by cordinGH** [Misuzu2027/syplugin-backlink-panel#27]
最近新增的功能选项（引用其他文档的定义块）超好用！查看相关块的反链巨方便！！
非常感谢作者大大的开发❤️

不过新增这个功能选项后，突然回想起了 #21  中有用户提到「臃肿」问题。我感觉或许并不是真的臃肿，而是因为插件的功能丰富，以至于新用户可能第一时间无法熟悉操作逻辑。

我觉得这或许和功能布局有关。对此，我做了如下调整：

* 给「反链链接」中的 文本搜索功能  ，追加一个 title —— `文本过滤`
* 将「筛选面板」中的 `关联的定义块` 更改为 `引用关联` ，并移动到「反向链接」中

调整后效果如下
![image](https://github.com/user-attachments/assets/fa94c384-9d9a-4ea3-8143-a6e3b55119dc)

而对于筛选面板，也做了title变更

* 当前文档定义块 → 谁的反链
* 反链所在文档 → 所在文档

![image](https://github.com/user-attachments/assets/3d8afeff-5d33-4770-ab07-4f9896024f04)

---

这么改动是为了让这两个面板的分工更加直白

* 「筛选面板」负责对 下方「反向链接」中的条目，做出 **来源性的筛选**，即 `谁的反链列表` `反链是从哪个页面出来的`
* 「反向链接」负责显示筛选结果，并支持对结果进一步过滤：
  1）通过文本检索的方式过滤
  2）通过引用关联的方式过滤

---

追加： 或许把 「筛选面板」 改名为「来源筛选」可能好一点？
![image](https://github.com/user-attachments/assets/237af59f-8c63-42b0-b58b-1d9548fd654d)

**Comment by cordinGH** [comment]
之所以我觉得这样调整能让面板更直白，是因为 `关联的定义块` 内的选项  并不是在当前文档内，而是在反链条目中的。
用户只会在看到了所想要的反链条目后（谁的反链 + 哪里出来的反链），才会通过 `关联的定义块` 或者 `文本过滤`，来对这些条目做出进一步过滤。

因此，我才觉得 `关联的定义块` 放在「反向链接」这一栏更合适。( title 从 `关联的定义块` 变更为 `引用关联` ）

**Comment by cordinGH** [comment]
对当前 issue 描述内容的修改次数，可能有点多（也是想着尽可能更清晰无歧义的表述）。不会再改动了，定型了。
![image](https://github.com/user-attachments/assets/b2d7b6ee-a066-4ec9-a4c3-2abdd54c8d91)

**Comment by cordinGH** [comment]
> 之所以我觉得这样调整能让面板更直白，是因为 `关联的定义块` 内的块选项 并不是在当前文档内，而是在反链条目中的。 用户只会在看到了所想要的反链条目后（谁的反链 + 哪里出来的反链），才会通过 `关联的定义块` 或者 `文本过滤`，来对这些条目做出进一步过滤。
> 
> 因此，我才觉得 `关联的定义块` 放在「反向链接」这一栏更合适。( title 从 `关联的定义块` 变更为 `引用关联` ）

issue - #25 中提类到的锚文本过滤需求，其实也完全可以通过现有的 `关联的定义块` 来实现，而不需要额外增加语法，就像下图这样：
![image](https://github.com/user-attachments/assets/b3ff6e80-e77b-4d21-8a5c-9c00388da65b)
然后我就可以click/shift+click 进行过滤。

**Comment by cordinGH** [comment]
@Misuzu2027  当前issue的反馈内容差不多就这些了。非常感谢作者大大开发这个插件，真的好用！也是希望这个插件可以被更多人喜欢

**Comment by Misuzu2027** [comment]
非常感谢肯定和建议。

文案方面，“当前文档定义块” 确实不再适用，打算改成：“定义块范围”。其他的暂不做修改。

下面的反链面板暂时不会去动，原因是从我个人使用上来说，现在的布局还算是比较顺手的，大部分时候打开反链面板使用排序和搜索就可以立马找到想要的内容，所以反链区域最好能够简洁一点；筛选面板就是更加进阶的用法，用来专心对一个主题进行汇总或创作时提升效率。

对于刚接触的用户来说，确实会感到有些迷惑，我的想法是劲量完善一下 README，然后有空的话写一个插件功能使用详解，发布在链滴，来降低理解和使用的门槛。

**Comment by cordinGH** [comment]
定义块范围这个名字可以，蛮贴切的。

布局的话，确实，熟悉用法之后，布局确实没什么影响，顺手为主。
尊重作者大大的选择。

**Comment by Misuzu2027** [comment]
v0.0.19 修改文案 “当前文档定义块”   为 “定义块范围”
