### ISSUE TITLE
子块反链不显示嵌入块

### ISSUE THREAD

**Issue by SaXz2** [Misuzu2027/syplugin-backlink-panel#29]
只有嵌入块的时候就不会显示，但是加一个块引用就会显示

![Clip_2024-11-24_14-37-50](https://github.com/user-attachments/assets/ec572a6e-89ca-4037-8c94-60e94954adfa)

![Clip_2024-11-24_14-38-24](https://github.com/user-attachments/assets/e9541dee-b4e0-4eb1-b842-d997a46a6f2f)

**Comment by Misuzu2027** [comment]
之前确实没有考虑过嵌入块的情况，把嵌入块融入反链这块逻辑也确实有点复杂，下个版本加上试试，同时会支持 嵌入块实际块内容 进行 文本搜索 和 关联定义块匹配。
