### ISSUE TITLE
【BUG反馈】反链面板展示不全

### ISSUE THREAD

**Issue by mozhux** [Misuzu2027/syplugin-backlink-panel#3]
如题，筛选面板有查出来多条，但反链面板只展示了10条
![7bf76157025d4bc5eacb2196d6d8e0ff](https://github.com/user-attachments/assets/497b9677-017e-49de-8833-4215c12c87ad)

**Comment by Misuzu2027** [comment]
因为每一个反链编辑区域，都维护了一个 ws 长连接，差不多等同于打开了一个文档；为了性能考虑就没有全部展示。下个版本会增加翻页功能，后续设置中也可以让用户自定义每一页显示反链的数量。

**Comment by mozhux** [comment]
> 因为每一个反链编辑区域，都维护了一个 ws 长连接，差不多等同于打开了一个文档；为了性能考虑就没有全部展示。下个版本会增加翻页功能，后续设置中也可以让用户自定义每一页显示反链的数量。

好的，那就是相当于反链面板还得主要看筛选面板上的操作。

**Comment by Misuzu2027** [comment]
v0.0.2 已上线 设置每页大小 和 翻页功能。

**Comment by mozhux** [comment]
> v0.0.2 已上线 设置每页大小 和 翻页功能。

体验了一下，整体不错的。就是个数和翻页在上面，但划下来就看不到了，这个就和要翻页这个动作冲突了，还得返回去翻页。建议上面悬浮呢？
![image](https://github.com/user-attachments/assets/afd30ff4-d1fd-47ad-9e70-5309e45c464b)

**Comment by Misuzu2027** [comment]
> 体验了一下，整体不错的。就是个数和翻页在上面，但划下来就看不到了，这个就和要翻页这个动作冲突了，还得返回去翻页。建议上面悬浮呢？

反链面板的翻页区域可以固定。筛选标题和面板要考虑一下，如果是展开状态下，需要把展开的面板一并固定吗，固定的话比较合逻辑不过会占空间；只固定筛选标题的话，如果移动的很下面，点展开或折叠还是会看不到筛选面板，可能会对用户造成疑惑。

> 看到有展开列表的功能，可能以后有人想要设置每次都自动展开所有列表，或者设置展开列表的层级。类似logseq在edn文件里设置那样。

这个好，后续调研一下 logseq 的交互逻辑，应该可以加在设置当中。

**Comment by mozhux** [comment]
> > 体验了一下，整体不错的。就是个数和翻页在上面，但划下来就看不到了，这个就和要翻页这个动作冲突了，还得返回去翻页。建议上面悬浮呢？
> 
> 反链面板的翻页区域可以固定。筛选标题和面板要考虑一下，如果是展开状态下，需要把展开的面板一并固定吗，固定的话比较合逻辑不过会占空间；只固定筛选标题的话，如果移动的很下面，点展开或折叠还是会看不到筛选面板，可能会对用户造成疑惑。
> 
> > 看到有展开列表的功能，可能以后有人想要设置每次都自动展开所有列表，或者设置展开列表的层级。类似logseq在edn文件里设置那样。
> 
> 这个好，后续调研一下 logseq 的交互逻辑，应该可以加在设置当中。

可能固定会有点复杂，后面有精力再考虑吧。不过翻页那个不固定的话最好是放到下面去。

**Comment by Misuzu2027** [comment]
v0.0.3 已实现顶部固定；支持设置默认展开列表项深度
