### ISSUE TITLE
插件优化的亿点点建议

### ISSUE THREAD

**Issue by QMike0** [Misuzu2027/syplugin-backlink-panel#4]
感谢佬的插件，真的大大加强了思源反链体验！
使用下来感觉整体已经很顺滑了，基本没有卡顿的感觉，不过还缺失一些功能，另外还有些细节可能需要再优化一下

## 功能方面
1. 目前插件在筛选锚文本/文档时，仅支持click实现“包含”，而尚未支持“排除”。可以类似于logseq一样，shift+click以进行锚文本/文档的排除
![image](https://github.com/user-attachments/assets/b7c355b2-c475-42a4-bbd0-4d32567fe7f5)
2. 支持一键展开、折叠全部反链，便于查看。
![image](https://github.com/user-attachments/assets/097a5754-a9d6-4c00-ae4e-30bdf044e86e)
3. 反链的关键词文本搜索并高亮显示。以思源自带的反链面板为例，可以搜索文本（任意文本，不是锚文本），然后筛选出包含该文本的反链，并高亮搜索的关键词：
![image](https://github.com/user-attachments/assets/e17bd214-f754-4482-a1d3-ec04c5090a6c)
这个文本搜索输入框可以放在反链区域右上方：
![image](https://github.com/user-attachments/assets/60839707-d379-4090-a8c2-709413b6c913)

## UI细节
个人感觉logseq的反链区域看着比较舒服些，可以类似地进行优化
1. 屏蔽反链的面包屑。说实话，在查看反链时，面包屑不仅没啥用，而且很干扰反链区域的观感
![image](https://github.com/user-attachments/assets/818a50f8-fd04-4ba0-b8af-dee1530dfa52)
2. 筛选区域的锚文本黑框淡化为灰色。现在有点太黑了hh，反链一多就感觉乌丫丫的
![image](https://github.com/user-attachments/assets/7893f8ad-ecbf-483e-af71-2a4c763027b4)
可以像logseq一样，细化这个黑框，并调为灰色：
![image](https://github.com/user-attachments/assets/66ef700a-618d-4837-a3bf-ecd70b473ce3)
3. 不同反链的各区域背景调为灰色，以进行区分，例如：
![image](https://github.com/user-attachments/assets/ad6560d6-d73c-4509-9961-811c80916203)
或者像思源自带的那样，对各反链的文档标题强化显示，以区分各反链（其实不如上面的好看）
4. 锚文本展示区域无需背景灰色，保持默认其实就很好看了。即使有很多反链，只展示滚动条就好，例如插件【文档层级展示】的展示效果：
![image](https://github.com/user-attachments/assets/1146632b-d357-47bd-8316-2841832ffb77)
PS：【关联的定义块】和【反链所在文档】的排序框和输入框连到一起了：
![image](https://github.com/user-attachments/assets/56731a98-3ee8-485a-b617-1593f9ed4d2c)
5. “共xx个反链”可以突出显示一下，例如加粗或者变成黑色：
![image](https://github.com/user-attachments/assets/639fdb6b-2f05-4e16-99f0-f974749c20dc)

## 其他
1. 佬能否考虑做下【静态锚文本】/【动态锚文本】的区分。原因是目前用这俩作为传递型双链/关联型双链的区分，若存在大量反链的情况下，不好直接判断出哪些是传递型双链。如果支持区分的话，就可以很方便通过【动态锚文本】判断出来哪些是传递型双链，也就是“双链标签”
2. 侧栏展示反链总感觉有点别扭，特别是笔记本小屏幕情况下就更难受了。看到佬后续计划继续做文档底部反链，能否将这个的优先级往前提一提呢，多谢！

**Comment by sweesalt** [comment]
支持一下，建议底部反链优先考虑

**Comment by Misuzu2027** [comment]
感谢建议，非常有用。
功能1：排除筛选条件，目前可以使用右键或双击实现，后续加上 shift + click 方式排除。

**Comment by Wetoria** [comment]
←_←，加油，赶紧取代enhance插件的底部反链

**Comment by QMike0** [comment]
> 功能1：排除筛选条件，目前可以使用右键或双击实现，后续加上 shift + click 方式排除。

了解，试了一下右键确实可以，之前没发现😂
不过双击好像不行

> 屏蔽反链的面包屑。说实话，在查看反链时，面包屑不仅没啥用，而且很干扰反链区域的观感

又重新用了下，发现存在`关联的定义块`的情况下，面包屑还是需要的，用于快速展开上下文，否则可能找不到`关联的定义块`在哪。
PS：筛选面板中的`当前文档定义块`、`关联的定义块`改名为`当前文档块引用`、`关联的块引用`或者`当前文档反链`、`关联的反链`会不会更清晰一些

**Comment by Misuzu2027** [comment]
> > 功能1：排除筛选条件，目前可以使用右键或双击实现，后续加上 shift + click 方式排除。
> 
> 了解，试了一下右键确实可以，之前没发现😂 不过双击好像不行
> 
> > 屏蔽反链的面包屑。说实话，在查看反链时，面包屑不仅没啥用，而且很干扰反链区域的观感
> 
> 又重新用了下，发现存在`关联的定义块`的情况下，面包屑还是需要的，用于快速展开上下文，否则可能找不到`关联的定义块`在哪。 PS：筛选面板中的`当前文档定义块`、`关联的定义块`改名为`当前文档块引用`、`关联的块引用`或者`当前文档反链`、`关联的反链`会不会更清晰一些

1. 双击可能是因为目前设置的默认双击间隔太短了，难以触发，后续加上 shift + click 后打算去除。
2. 面包屑在切换层级的时候是有必要的，后续不会去除，如果不打算使用可以通过 自定义CSS 进行隐藏。
3. 关于命名，我个人结合官方命名的理解是
   * 定义块：文档中被引用的块。
   * 引用块：当前文档引用其他文档的“定义块”。
   * 反链块：定义块被引用后所在的块。
