### ISSUE TITLE
插件优化的又亿点点建议

### ISSUE THREAD

**Issue by QMike0** [Misuzu2027/syplugin-backlink-panel#5]
> 十分感谢佬对我之前所提issue的重视，提到的改进基本都实现了，甚至在设置中给出了`隐藏面包屑`的按钮hh
多谢🙏

言归正传
## 存在的问题
1. 反链数量提示异常，如图所示：
![image](https://github.com/user-attachments/assets/2927c781-91a1-4fee-8223-5c58d58a9fc2)
仔细搜查后发现，本插件对反链的搜索其实没有问题，而是由于本插件是以“反链所在的内容块”的数量为基准统计数量，而非块引用数。这里，我在`test`和`test-AI`两个文档进行测试，`test-AI`中分别引用`test`文档的两个不同内容块：
![image](https://github.com/user-attachments/assets/a9ef42cd-4cac-4d4b-8789-672596380d65)
`test`文档显示有两个反链：
![image](https://github.com/user-attachments/assets/3efb1c38-d12b-48ac-a309-2248f95c4cd6)
思源自带反链面板由于统计的是块引用数，所以显示两个反链，但只展示一个内容块：
![image](https://github.com/user-attachments/assets/1d00d153-a445-4222-8b48-c6a4f04ffb65)
本插件反链面板则显示只有1个反链：
![image](https://github.com/user-attachments/assets/a94be1ce-20bd-4e72-8571-ae2299f000ae)
可能的解决方法：个人觉得，由于本插件的特点（不是基于文档来显示反链，而是基于内容块），可以提示两个内容：“共xx个反链，xx个内容块“。`反链`表示块引用数，`内容块`表示反链所在内容块数，从而避免大家误以为本插件对反链的统计有缺漏
2. 设置中应提供每页展示内容块数量的上限调节。现在默认每页最多展示8个内容块（有时候是7个）：
![image](https://github.com/user-attachments/assets/779f1ae1-75f9-4027-b7fe-7f8c9094829d)
![image](https://github.com/user-attachments/assets/2e8abf73-cdc9-4fee-bacf-4a56cc2e526c)
设置中有个`页数`选项，不晓得这个是干啥用的，好像和每页展示反链块数量无关，设置数量也无法改变：
![image](https://github.com/user-attachments/assets/8d7665d7-9c5c-4b61-bbdd-4896680dc209)
3. 移动端中，底部反链会在文档底部展示，但似乎不起作用，无法显示当前文档的任何反链。
当然佬假如有空，能做下移动端的适配就最好了。
## 功能期待
1. 当前底部反链在所有文档统一展示/不展示，期待能通过添加块属性/插件设置/快捷键的方式，使得部分文档展示或不展示底部反链，并能记忆哪些文档展示/不展示底部反链
2. 为反链面板的每个内容块都添加便于后期整理的功能，包括但不限于复制、移动、复制为块引用等（具体可参考插件“番茄工具箱”），相应按钮可添加在反链区域每个内容块的标题处（可能需要限制标题长度）：
![image](https://github.com/user-attachments/assets/1fa193c1-11d0-4f46-a8fd-5467339f3169)

## 其他 - 个人建议
> 下面的功能/UI优化是我自己的需求或主观想法，特别是UI方面只是个人审美，仁者见仁

1. 筛选面板的“反链所在文档”处或“保存当前条件”右方提供在当前文档中导入**反链所在文档块**的功能，导出为列表形式，便于后期整理为moc
PS：只需导入粒度为**文档块**即可，而不是细化到反链所在的每个内容块，想法是这样便于将笔记库中各处散乱的文档面向主题地统一管理，具体可参考[如何进行知识管理丨 MOC：面向主题地去管理笔记链接](https://ld246.com/article/1715446523024)
2. UI方面，底部反链区域过宽，可以适当收窄一点。现在除非使用F佬的插件【编辑器宽度】，否则正文的宽度明显会小于底部反链的宽度范围，割裂感会有点强。具体宽度可按照思源提供的“自适应宽度“。或再略窄些
4. 底部反链的“筛选面板”与“反向链接”之间无需分割线，但可考虑在“筛选面板”上方与正文之间存在分割线：
![image](https://github.com/user-attachments/assets/8db75a08-57aa-45db-ba6b-6336fb2e27e9)
5. 反链区域的标题与内容块宽度不一致，可以考虑进行统一。
原因是我在添加CSS后，发现反链区域的标题与下方内容块会明显地宽度不一致，以Asri主题为例（默认主题下也是这样）：
```
.backlink-panel-document-bottom__area .backlinkList .sy__backlink .protyle .protyle-content {
    background-color: rgb(232,236,240);
}
```
![image](https://github.com/user-attachments/assets/e53126ce-e429-4605-8e1c-697a6990cef7)
统一宽度应该会好看一些（当然这个做不做都无伤大雅）
6. 底部反链的“筛选面板”与“反向链接”两处无需默认为灰色，保持默认背景色可能更好些。鼠标放上去后再变为灰色
![image](https://github.com/user-attachments/assets/da254db9-f0ac-407b-8db9-d86a7178cb6a)

**Comment by Misuzu2027** [comment]
* 问题1：改为 “共 x 个反链块” 
  * 显示两个数字怕用户理解上有偏差，分不清到底哪个是总数。
  * 吐槽一下官方的反链去重，列表项的反链可以去重，但是段落当中的不会去重。。
    *  ![image](https://github.com/user-attachments/assets/1c3c5c76-ccc2-426b-a70a-fbbd1ed53ae3)
* 问题2：bug ，页数就是设置页面大小的，优化一下文案，改为：每页反链块数量
* 问题3：手机端慢慢来。。
* 功能1：这个正在做，后续可以通过点击 文档块标 的菜单或快捷键进行设置，让文档 一直显示/不显示 底部反链。
* 功能2：可以考虑。
* 其他1：不考虑了，可以借助模板实现。
* 其他2：后续劲量跟文档边距一致。
* 其他3：好。
* 其他4：这个确实跟主题关系较大，我这里主要保持跟官方样式一直。
* 其他5：发现没有5，直接到6了
* 其他6：这里还是需要背景色的，因为在滚动的时候，标题会置顶，如果透明的就会出现被覆盖元素重叠的情况。
  * ![image](https://github.com/user-attachments/assets/d682fb28-36b9-4b01-8c22-3d5baaef8d49)

**Comment by QMike0** [comment]
再反映几个问题/可以改进的地方，供参考：
1. 对于”关联的定义块“，当同时存在对同一内容块的静态和动态锚文本时，静态锚文本的优先级更高，使得对应的动态锚文本在筛选中不显示。
例如我这里创建了四个文档：
![image](https://github.com/user-attachments/assets/150a4049-e461-4f80-bb72-4de07ff78cd1)
其中，test文档以**动态锚文本**引用test3文档，同时也引用test-AI文档：
![image](https://github.com/user-attachments/assets/9979c453-bc6c-4821-8f4a-d2fc244ea9a2)
test文档以**静态锚文本**引用test3文档，同时也引用test-AI文档：
![image](https://github.com/user-attachments/assets/c88a5d34-4baf-4f17-95bd-0a9ddcb9fcf4)
此时在test-AI中查看”关联的定义块“，会发现将这两个引用都归入”静态锚文本“：
![image](https://github.com/user-attachments/assets/c6228af3-ce74-4c77-8daa-ec5b6edc1610)
![image](https://github.com/user-attachments/assets/81d7dc9b-26e1-4e0c-8bfe-9f7542ea1aea)
![image](https://github.com/user-attachments/assets/00fd3eea-9407-4720-91e3-acf5e6f1202b)
能否将这种情况下的动态和静态锚文本进行区分，或者提高动态锚文本的优先级
2. 锚文本后的数字区域固定，双位数或多位数时会与前面的锚文本重合：
![image](https://github.com/user-attachments/assets/7db19cca-08b2-41a5-a30b-dfc70996ab0b)
3. （功能增强）可不可以考虑支持底部反链的文档标题区域点击后跳转到相应文档中，现在是折叠/展开，感觉不方便去反链的原文查看
![image](https://github.com/user-attachments/assets/c9d1d6c4-e372-4417-8e8d-f67276d0dcb0)

**Comment by Misuzu2027** [comment]
1. 算是一个bug，下个版本修复。
2. 收到。
3. 目前跟官方的逻辑一致，按住 Ctrl + 点击 文档名 可以跳转到指定文档。

**Comment by QMike0** [comment]
> 目前跟官方的逻辑一致，按住 Ctrl + 点击 文档名 可以跳转到指定文档。

好的，又学到一个小技巧

**Comment by Misuzu2027** [comment]
此 issue 的建议差不多已经完成，如果有还问题可以回复或开新的。

**Comment by QMike0** [comment]
> 此 issue 的建议差不多已经完成，如果有还问题可以回复或开新的。

感谢大佬！
