### ISSUE TITLE
文档底部反链面板的建议

### ISSUE THREAD

**Issue by sweesalt** [Misuzu2027/syplugin-backlink-panel#8]
![image](https://github.com/user-attachments/assets/7d296fc0-5e36-4623-bc02-054d8f69947e)

**Comment by Misuzu2027** [comment]
要不这样，还是开关，开就是 3，关就是2 。

**Comment by sweesalt** [comment]
> 要不这样，还是开关，开就是 3，关就是2 。

嗯嗯，这样没问题👍

**Comment by Misuzu2027** [comment]
v0.0.7 已更新
