### ISSUE TITLE
反链面板宽度能否设置成和正文宽度一致？

### ISSUE THREAD

**Issue by sweesalt** [Misuzu2027/syplugin-backlink-panel#9]
![image](https://github.com/user-attachments/assets/f2e7b9c8-3d2d-46c2-b969-8c8c8529a61a)

**Comment by sweesalt** [comment]
我思源编辑器选项为“自适应宽度”。

**Comment by Misuzu2027** [comment]
好的，我是配一下。

**Comment by Misuzu2027** [comment]
增加了一个设置，可以手动设置间距，你想要跟文档一致的话，填空即可
![image](https://github.com/user-attachments/assets/04b319b1-a859-4d58-b7f5-5af6a58f0ae1)
